### PR TITLE
Handle overflow

### LINKED ISSUE #47: Overflow with `(is)/2`
```
$ ./bin/gprolog
GNU Prolog 1.6.0 (64 bits)
Compiled Jun 27 2023, 16:35:39 with gcc
Copyright (C) 1999-2023 Daniel Diaz

| ?- current_prolog_flag(max_integer, V), W is V + 1.

V = 1152921504606846975
W = -1152921504606846976

yes
| ?-
```

### PR DESCRIPTION
**Pull request by notoria**
Resolves #47 .

### CODE REVIEW

**Comment by notoria** [comment]
A check is added in `add`, `sub`, `inc`, `dec`, `mul`, `div`, `rem`, `neg`, `abs`, `gcd`.

**Comment by didoudiaz** [comment]
Thank you for your PR !
I have to review it (e.g. I'm not sure we want these tests in fast-math mode).
OK to discuss by email (didou dot diaz at gma...com) ?

**Comment by notoria** [comment]
Yes, we can discuss.
------- Original Message -------

**Comment by notoria** [comment]
I sent the mail.

**Pull request closed without merging**
